// <auto-generated />
using System;
using Artikelverwaltungssystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artikelverwaltungssystem.Migrations
{
    [DbContext(typeof(ArtikelDbContext))]
    partial class ArtikelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Artikelverwaltungssystem.Models.Abteilung", b =>
                {
                    b.Property<int>("AbteilungsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AbteilungsID");

                    b.ToTable("Abteilungen");
                });

            modelBuilder.Entity("Artikelverwaltungssystem.Models.Artikel", b =>
                {
                    b.Property<int>("ArtikelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbteilungsID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventarnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seriennummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArtikelID");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("Artikelverwaltungssystem.Models.Historie", b =>
                {
                    b.Property<int>("HistorienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlteAbteilung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtikelID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeaendertAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NeueAbteilung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HistorienID");

                    b.ToTable("Historien");
                });

            modelBuilder.Entity("Artikelverwaltungssystem.Models.Verbrauchsart", b =>
                {
                    b.Property<int>("VerbrauchsartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VerbrauchsartID");

                    b.ToTable("Verbrauchsarten");
                });

            modelBuilder.Entity("Artikelverwaltungssystem.Models.Verbrauchsbuchung", b =>
                {
                    b.Property<int>("VerbrauchsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbteilungsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Menge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerbrauchsartID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VerwendetAm")
                        .HasColumnType("TEXT");

                    b.HasKey("VerbrauchsID");

                    b.ToTable("Verbrauchsbuchungen");
                });
#pragma warning restore 612, 618
        }
    }
}
